repos:
  - repo: local
    hooks:
      # 1) Ruff Formatter - auto-format code (style only, like Black)
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff
        args: ["format", "--force-exclude"]
        language: system
        types: [python]

      # 2) Ruff linter (safe autofix) - catch issues + auto-fix safe ones
      - id: ruff-lint-safe-fix
        name: ruff check (safe autofix)
        entry: .venv/bin/ruff
        args: ["check", "--fix", "--show-fixes", "--output-format", "full", "--force-exclude"]
        language: system
        types: [python]

      # 3) Ruff linter (verify only) - final check, fail if issues remain
      - id: ruff-lint-verify
        name: ruff check (verify, fail if issues remain)
        entry: .venv/bin/ruff
        args: ["check", "--output-format", "full", "--force-exclude"]
        language: system
        types: [python]

      # 4) Pyright - Static type checking
      - id: pyright
        name: pyright (type checking)
        entry: .venv/bin/pyright
        language: system
        types: [python]
        args: ["--project", "pyrightconfig.jsonc"]

      # 5) Pytest - Run tests before committing
      - id: pytest
        name: pytest (run tests)
        entry: .venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false   # don't pass staged filenames, run full suite
        always_run: true        # run even if no Python files changed
        args: ["-x"]            # -x = fail fast


# Default Python for pre-commit hooks
default_language_version:
  python: python3
