repos:
  # ================================================================================================================== #
  #                                                       RUFF                                                        #
  # ================================================================================================================== #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # 1) Ruff Formatter — auto-format code (style only, like Black)
      - id: ruff-format

      # 2) Ruff Linter (safe autofix) — catch issues + auto-fix safe ones
      - id: ruff
        name: ruff check (safe autofix)
        args: ["--fix", "--show-fixes", "--output-format", "full"]

  # ================================================================================================================== #
  #                                                  PYRIGHT + PYTEST                                                 #
  # ================================================================================================================== #
  - repo: local
    hooks:
      # 3) Pyright — strict static type checking (project mode)
      - id: pyright
        name: pyright (type checking)
        language: python
        entry: pyright
        pass_filenames: false                     # analyze the whole project
        args: ["--project", "pyrightconfig.jsonc"]
        additional_dependencies:
          - pyright>=1.1.404
          - pytest>=8                             # ensures pytest is importable for fixtures in typing context

      # 4) Pytest — run the full suite before committing
      - id: pytest
        name: pytest (run tests)
        language: python
        entry: pytest
        pass_filenames: false                     # run full suite (not per-file)
        always_run: true                          # even if no Python files changed
        args: ["-x", "-q"]                        # -x = fail fast, -q = quiet but informative
        additional_dependencies:
          - pytest>=8
