repos:
  # ================================================================================================================== #
  #                                                       RUFF                                                        #
  # ================================================================================================================== #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2   # (Ruff requires 'v')
    hooks:
      # 1) Ruff Formatter — auto-format code (style only, like Black)
      - id: ruff-format

      # 2) Safe autofix — quiet, doesn’t block
      - id: ruff
        name: ruff check (safe autofix)
        args: ["--fix", "--quiet"]

      # 3) Final check — fails if anything left, shows full diagnostics
      - id: ruff
        name: ruff check (final, fail if issues)
        args: ["--output-format", "full"]

  # ================================================================================================================== #
  #                                               BASEDPYRIGHT + PYTEST                                               #
  # ================================================================================================================== #
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.5    # (basedpyright no 'v')
    hooks:
      # 3) BasedPyright — strict static type checking (project mode)
      - id: basedpyright
        name: basedpyright (type checking)
        pass_filenames: false                     # analyze the whole project
        args: ["--project", "pyrightconfig.jsonc"]
        additional_dependencies:
          - pytest>=8                             # ensures pytest is importable for fixtures in typing context

  - repo: local
    hooks:
      # 4) Pytest — run the full suite before committing
      - id: pytest
        name: pytest (run tests)
        language: system
        entry: .venv/bin/pytest
        pass_filenames: false          # run full suite
        always_run: true               # even if no Python files changed
        # args: []                     # rely entirely on pytest.ini (no -q!)
